{
    'name': 'GC Apartamentos',
    'version': '1.0.0',
    'license': 'LGPL-3',
    'author': 'Gestor Consultoría',
    'category': 'Real Estate',
    'summary': 'Gestión de apartamentos y unidades habitacionales',
    'description': 'Módulo para la gestión de apartamentos, edificios y unidades en Odoo Community 18.',
    'depends': ['base', 'mail', 'web', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/apartamento_views.xml',
        'views/valores_conceptos_views.xml',
        'views/account_move_views.xml',
        'views/multas_views.xml',
        'views/multas_menu.xml',
        'views/report_invoice_document_apartamento.xml',
        'wizard/wizard_generar_facturas_views.xml',
        'data/ir_ui_view_account_reconciliation_file.xml',
        'data/ir_ui_menu_account_reconciliation_file.xml',
    ],
    'images': ['static/description/icon.png'],
    'assets': {
        'web.assets_backend': [
            'gc_apartamentos/static/src/js/arrendatarios_control.js',
            'gc_apartamentos/static/src/css/grouping.css',
            'gc_apartamentos/static/src/js/grouping_width.js',
        ],
    },
    'web_icon': '/gc_apartamentos/static/description/icon.png',
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}