{
    'name': 'Property Owner Association',
    'version': '1.0.3',
    'category': 'Services',
    'depends': [
        'account',
        'calendar',
        'contacts',
        'mail',
        'product',
        'sale',
    ],
    'external_dependencies': {
        'python': ['openpyxl'],
    },
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_server.xml',
        'data/account_analytic_plan.xml',
        'data/ir_filters.xml',
        'data/ir_default.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/x_buildings_tag.xml',
        'data/x_properties_types.xml',
        'data/x_properties_tag.xml',
        'data/x_meters.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/res_company.xml',
        'demo/x_buildings.xml',
        'demo/account_analytic_account.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/helpdesk_team.xml',
        'demo/helpdesk_ticket.xml',
    ],
    'license': 'LGPL-3',
    'author': 'Gestor Consultoría',
    'website': 'https://www.gestorconsultoria.com.co',
    'installable': True,
    'auto_install': False,
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
