from . import sucursales
from . import zonas
from . import citys
from . import hr_employee
from . import productos_team
from . import planes_team
from . import rp_team
from . import reconocimiento_logistico_team
from . import hogar
from . import pyme
# from . import pos_order_inherit
from . import archivos
from . import comisiones
from . import ventas_tips
from . import cruce_tips
from . import presupuestos
from . import sims_prendidas
from . import aepas
from . import cartera
from . import kit_prepagos
from . import digesto
from . import res_users
from . import descuentos
from . import biometrias
from . import clientes_team
