# -*- coding: utf-8 -*-
from odoo import models, fields, api
from odoo.exceptions import ValidationError


class rpTEAM(models.Model):
    _name = 'gestor.rp.team'
    _description = 'RP TEAM'

    name = fields.Char('Archivo importado')
    fecha_procesamiento = fields.Date('Fecha de procesamiento')
    distribuidor = fields.Char('DISTRIBUIDOR')
    distribuidor_id = fields.Many2one('gestor.sucursales')
    producto = fields.Char('PRODUCTO')
    producto_id = fields.Many2one('gestor.productos.team')
    descripcion = fields.Char('DESCRIPCION')
    co_id = fields.Char('CO_ID')
    planilla = fields.Char('PLANILLA')
    activacion = fields.Char('ACTIVACION')
    min = fields.Char('MIN', index=True)
    imei = fields.Char('IMEI', index=True)
    iccid = fields.Char('ICCID')
    custcode = fields.Char('CUSTCODE')
    fecharecepcion = fields.Char('FECHARECEPCION')
    fechalegalizacion = fields.Char('FECHALEGALIZACION')
    fechadevolucion = fields.Char('FECHADEVOLUCION')
    fechasolucion = fields.Char('FECHASOLUCION')
    causal1 = fields.Char('CAUSAL1')
    causal2 = fields.Char('CAUSAL2')
    causal3 = fields.Char('CAUSAL3')
    causal4 = fields.Char('CAUSAL4')
    causal5 = fields.Char('CAUSAL5')
    desc = fields.Char('DESC')
    cfm_mes_1 = fields.Char('CFM_MES_1')
    estado_mes_1 = fields.Char('ESTADO_MES_1')
    cfm_mes_2 = fields.Char('CFM_MES_2')
    estado_mes_2 = fields.Char('ESTADO_MES_2')
    cfm_mes_3 = fields.Char('CFM_MES_3')
    estado_mes_3 = fields.Char('ESTADO_MES_3')
    cfm_mes_4 = fields.Char('CFM_MES_4')
    estado_mes_4 = fields.Char('ESTADO_MES_4')
    cfm_mes_5 = fields.Char('CFM_MES_5')
    estado_mes_5 = fields.Char('ESTADO_MES_5')
    cfm_mes_6 = fields.Char('CFM_MES_6')
    estado_mes_6 = fields.Char('ESTADO_MES_6')
    prim_llamada_activacion = fields.Char('PRIM_LLAMADA_ACTIVACION')
    fecha_cierre_altas=fields.Date('FECHA_CONTROL_PAGO')
    legalizacion = fields.Char('LEGALIZACION')
    recepcion = fields.Char('RECEPCION')
    devolucion = fields.Char('DEVOLUCION')
    solucion = fields.Char('SOLUCION')
    vozxmin = fields.Char('VOZXMIN')
    smsxmin = fields.Char('SMSXMIN')
    gprsxmin = fields.Char('GPRSXMIN')
    diasxmin = fields.Char('DIASXMIN')
    cargas_mes_min_1 = fields.Char('CARGAS_MES_MIN_1')
    cargas_mes_min_2 = fields.Char('CARGAS_MES_MIN_2')
    cargas_mes_min_3 = fields.Char('CARGAS_MES_MIN_3')
    cargas_mes_min_4 = fields.Char('CARGAS_MES_MIN_4')
    cargas_mes_min_5 = fields.Char('CARGAS_MES_MIN_5')
    cargas_mes_min_6 = fields.Char('CARGAS_MES_MIN_6')
    codigo_distribuidor = fields.Char('CODIGO_DISTRIBUIDOR')
    fecha_reposicion = fields.Char('FECHA_REPOSICION')
    permanencia_pendiente = fields.Char('PERMANENCIA_PENDIENTE')
    fecha_de_recepcion = fields.Char('FECHA_DE_RECEPCION')
    fecha_de_legalizacion = fields.Char('FECHA_DE_LEGALIZACION')
    fecha_de_devolucion = fields.Char('FECHA_DE_DEVOLUCION')
    fecha_de_solucion = fields.Char('FECHA_DE_SOLUCION')
    ivr = fields.Char('IVR')
    mes1 = fields.Char('MES1')
    mes2 = fields.Char('MES2')
    mes3 = fields.Char('MES3')
    mes4 = fields.Char('MES4')
    mes5 = fields.Char('MES5')
    mes6 = fields.Char('MES6')
    valor_microcargas = fields.Char('VALOR_MICROCARGAS')
    cantidad_microcargas = fields.Char('CANTIDAD_MICROCARGAS')
    source_name = fields.Char('SURCE NAME')
    producto1 = fields.Char('PRODUCTO1')
    producto2 = fields.Char('PRODUCTO2')
    tipo_linea = fields.Char('TIPO LÍNEA')
    agent_code = fields.Char('AGENT CODE')
    agent_name = fields.Char('AGENT NAME')
    activacion_1 = fields.Char('ACTIVACION.1')
    codigo_distribuidor = fields.Char('Cod. Distribuidor')
    tipo_convergencia = fields.Char('Tipo de Convergencia')
    mdistribuidor = fields.Char('MDISTRIBUIDOR')
    co_id_1 = fields.Char('CO_ID_1')
    prim_llamada_activacion_1 = fields.Char('PRIM_LLAMADA_ACTIVACION_1')
    ivr_1 = fields.Char('IVR_1')
    planilla_1 = fields.Char('PLANILLA_1')
    min_1 = fields.Char('MIN_1')
    imei_1 = fields.Char('IMEI_1')
    iccid_1 = fields.Char('ICCID_1')
    custcode_1 = fields.Char('CUSTCODE_1')
    fecha_de_legalizacion_1 = fields.Char('FECHA_DE_LEGALIZACION_1')
    fecha_de_recepcion_1 = fields.Char('FECHA_DE_RECEPCION_1')
    mes1_1 = fields.Char('MES1_1')
    tipo_archivo = fields.Char('Tipo de Archivo')
    nombre_archivo = fields.Char('Tipo de Archivo')
    tipo_venta = fields.Char('Tipo de Venta')
    tipo_de_convergencia = fields.Char('Tipo de Convergencia')


    # _sql_constraints = [('unq_DP_team_name', 'UNIQUE (co_id, imei, min, iccid, activacion)',
    #                     'El registro ya existe!')
    #                    ]


    class PortabilidadPrepago(models.Model):
        _name = 'gestor.portabilidad.prepago'
        _description = 'Portabilidades Prepago'

        name = fields.Char('Número de Solicitud Interno')
        producto = fields.Char('Producto')
        fecha_solicitud = fields.Char('Fecha de Solicitud')
        estado_solicitud = fields.Char('Estado solicitud')
        min_a_portar = fields.Char('Min a portar')
        distribuidor = fields.Char('Distribuidor')
        operador_donante = fields.Char('Operardor donante')
        cedula_vendedor = fields.Char('Numero de Cedula vendedor')
        vendedor_tips = fields.Char('Vendedor Tips')
        tipo_vendedor = fields.Char('Tipo de vendedor')

    class PPagoComision(models.Model):
        _name = 'gestor.pago.comision'
        _description = 'Pago Comisiones'

        nit = fields.Char('NIT')
        fuerzadeventa = fields.Char('FUERZADEVENTA')
        region = fields.Char('REGION')
        canaldeventa = fields.Char('CANALDEVENTA')
        dealerpadre = fields.Char('DEALERPADRE')
        subfuerzadeventa = fields.Char('SUBFUERZADEVENTA')
        dealerhijo = fields.Char('DEALERHIJO')
        coid = fields.Char('COID')
        numerodetelefono = fields.Char('NUMERODETELEFONO')
        tipodeplan = fields.Char('TIPODEPLAN')
        codigodelplan = fields.Char('CODIGODELPLAN')
        desplanservadicionalpaq = fields.Char('DESPLANSERVADICIONALPAQ')
        concepto_bonificacion = fields.Char('CONCEPTO BONIFICACION')
        bonificacion = fields.Char('BONIFICACION')
        concepto_cesantia = fields.Char('CONCEPTO CESANTIA')
        cesantia = fields.Char('CESANTIA')
        estatusdecomision = fields.Char('ESTATUSDECOMISION')
        motivodelrechazoga1 = fields.Char('MOTIVODELRECHAZOGA1')
        motivodelrechazoga2 = fields.Char('MOTIVODELRECHAZOGA2')
        motivodelrechazoga3 = fields.Char('MOTIVODELRECHAZOGA3')
        motivodelrechazoga4 = fields.Char('MOTIVODELRECHAZOGA4')
        motivodelrechazoga5 = fields.Char('MOTIVODELRECHAZOGA5')
        motivodelrechazoga6 = fields.Char('MOTIVODELRECHAZOGA6')
        estadodelalinea = fields.Char('ESTADODELALINEA')
        fechadeactivacion = fields.Char('FECHADEACTIVACION')
        fechaderecepcion = fields.Char('FECHADERECEPCION')
        fechadelegalizacion = fields.Char('FECHADELEGALIZACION')
        fechadecorte = fields.Char('FECHADECORTE')
        fechadedesactivacion = fields.Char('FECHADEDESACTIVACION')
        fechadedevolucion = fields.Char('FECHADEDEVOLUCION')
        fechadesolucion = fields.Char('FECHADESOLUCION')
        llamada1si0no = fields.Char('LLAMADA1SI0NO')
        dupla = fields.Char('DUPLA')
        nombredelcliente = fields.Char('NOMBREDELCLIENTE')
        ceduladeciudadaniacliente = fields.Char('CEDULADECIUDADANIACLIENTE')
        custcode = fields.Char('CUSTCODE')
        iccid = fields.Char('ICCID')
        marca = fields.Char('MARCA')
        imei = fields.Char('IMEI')
        causaldeactivacion = fields.Char('CAUSALDEACTIVACION')
        codigodereglaquepagolacom = fields.Char('CODIGODEREGLAQUEPAGOLACOM')
        origen = fields.Char('ORIGEN')
        diasdeconsumo = fields.Char('DIASDECONSUMO')
        cantidaddemindeconsumo = fields.Char('CANTIDADDEMINDECONSUMO')
        valortotcargporperiodo = fields.Char('VALORTOTCARGPORPERIODO')
        monto_carga = fields.Char('MONTO_CARGA')
        periododelacarga = fields.Char('PERIODODELACARGA')

        _sql_constraints = [('unq_gestor_pago_comision', 'UNIQUE (coid, bonificacion, cesantia, monto_carga, periododelacarga)',
                        'El registro ya existe!')
                       ]
