# -*- coding: utf-8 -*-
{
    'name': 'SICONE - Cash Flow y Gestión de Proyectos',
    'version': '1.0.0',
    'category': 'Construction',
    'summary': 'Sistema de cotizaciones y gestión de proyectos de construcción',
    'author': 'AI-MindNovation',
    'website': 'https://www.ai-mindnovation.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'web',
    ],
    'external_dependencies': {
        'python': ['openpyxl'],
    },
    'data': [
        'security/sicone_security.xml',
        'security/ir.model.access.csv',
        'views/navbar_brand.xml',
        'data/secuencias.xml',
        'data/sicone_contable_data.xml',
        'views/cotizacion_views.xml',
        'views/cotizacion_version_views.xml',
        'views/proyecto_views.xml',
        'views/contable_views.xml',
        'views/empresa_views.xml',
        'views/wizard_nueva_cotizacion_view.xml',
        'views/wizard_carga_historica_view.xml',
        'views/wizard_libro_auxiliar_view.xml',
        'views/wizard_carga_ajustes_view.xml',
        'views/ajuste_conciliacion_views.xml',
        'views/dashboard_graphs_views.xml',
        'views/inversion_temporal_views.xml',
        'views/tasa_referencia_views.xml',
        'views/timeline_inversiones_views.xml',
        'views/sicone_tercero_views.xml',
        'views/proyeccion_gerencial_views.xml',
        'views/sicone_informes_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sicone/static/src/css/brand.css',
            'sicone/static/lib/chart.umd.min.js',
            'sicone/static/src/js/waterfall.js',
            'sicone/static/src/js/timeline.js',
            'sicone/static/src/js/proyeccion.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/banner.png', 'static/description/icon.png'],
}
